# Generated by Django 6.0 on 2026-03-06 01:51

import django_minio_backend.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'video_file',
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name='microservices-bucket', storage_name='default'
                        ),
                        upload_to='videos/',
                    ),
                ),
                (
                    'zip_video_file',
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name='microservices-bucket', storage_name='default'
                        ),
                        upload_to='videos-processed/',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
