services:
  image_processing_service:
    container_name: image-processing-service
    restart: unless-stopped
    networks:
      - shared_network

volumes:
  database:

networks:
  shared_network:
    driver: bridge
