name: image-processing-system

services:
  image_processing_service:
    build:
      context: .
      args:
        MODE: development
    environment:
      MODE: development
      BASE_URL: http://localhost:8001
      LOGS_ROOT: /var/log/image_processing_service/
      STATIC_ROOT: /var/www/image_processing_service/static/
      MEDIA_ROOT: /var/www/image_processing_service/media/
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
